### ISSUE TITLE
Crash in -[ADJActivityHandler initI:preLaunchActionsArray:]

### ISSUE THREAD

**Issue by Nebary** [adjust/ios_sdk#384] opened 2019-08-14 20:34 UTC
We started observing this new crash in our app. Might be related to the upgrade to 4.18.0

```
Crashed: io.adjust.ActivityQueue
EXC_BAD_ACCESS KERN_INVALID_ADDRESS 0x000001a1b3462ff9
-[ADJActivityHandler initI:preLaunchActionsArray:]
```

```
io.adjust.ActivityQueue
0  libobjc.A.dylib                0x18042891c objc_msgSend + 28
1  Adjust                         0x105136d24 -[ADJActivityHandler initI:preLaunchActionsArray:] + 340
2  Adjust                         0x105134780 __52-[ADJActivityHandler initWithConfig:savedPreLaunch:]_block_invoke_2 + 92
3  Adjust                         0x10515f774 __42+[ADJUtil launchInQueue:selfInject:block:]_block_invoke + 48
4  libdispatch.dylib              0x180b4cb24 _dispatch_call_block_and_release + 24
5  libdispatch.dylib              0x180b4cae4 _dispatch_client_callout + 16
6  libdispatch.dylib              0x180b56a38 _dispatch_queue_serial_drain$VARIANT$mp + 608
7  libdispatch.dylib              0x180b57380 _dispatch_queue_invoke$VARIANT$mp + 336
8  libdispatch.dylib              0x180b57d4c _dispatch_root_queue_drain_deferred_wlh$VARIANT$mp + 340
9  libdispatch.dylib              0x180b6011c _dispatch_workloop_worker_thread$VARIANT$mp + 668
10 libsystem_pthread.dylib        0x180e7fe70 _pthread_wqthread + 860
11 libsystem_pthread.dylib        0x180e7fb08 start_wqthread + 4
```

So far only one crash, but I rather create issue maybe this one is something known.

More info on environment:
```
# Platform: ios
# Date: 2019-08-14T00:28:00Z
# OS Version: 11.3.1 (15E302)
# Device: iPhone 6 Plus
# RAM Free: 7.6%
# Disk Free: 8%
```

**Comment by Nebary** [comment] 2019-08-14 20:39
Can it be memory related issue?

**Comment by uerceg** [comment] 2019-08-30 21:27
Hi @Nebary 

And sorry for a bit of delay in reply. Hm. Indeed on first sight it looks like it might be memory related issue, but then again, can't say anything for sure to back up that theory. RAM seems to be low, but again, can't say anything for sure. On our end, we were completely unable to reproduce this issue.

Did you maybe see any crash like this one or is this the only one you saw?

**Comment by uerceg** [comment] 2019-09-17 11:54
Closing this one for now, but in case you stumble upon more crashes like this and maybe have some additional information on the crash itself, please feel free to share it with us and reopen the issue.

**Closed by uerceg** 2019-09-17 11:54 UTC
