### ISSUE TITLE
Crash on iOS 8 Jailbroken devices when using Carthage

### ISSUE THREAD

**Issue by hovox** [adjust/ios_sdk#178] opened 2016-03-18 10:30 UTC
Hi,

We have updated our Adjust SDK with carthage to version `4.5.4`, here is a cartfile line for adjust:

`github "adjust/ios_sdk" == 4.5.4`

After going to live, we have started to receive crashes from iOS 8 Jailbroken devices:

here is the crash log:

`Fatal Exception: NSInvalidArgumentException
(null): unrecognized selector sent to class 0x1015c8ff8`

this crash happening on this line:

`ADJConfig *adjustConfig = [ADJConfig configWithAppToken:adjustAppToken environment:ADJEnvironmentProduction];`

I'm supposing that this crash happening because Adjust SDK is not loading on that devices.
If it's true, we can disable Adjust by this check:

``` Objective-C
    Class klass = NSClassFromString(@"ADJConfig");
    if (!klass) {
        return;
    }
```

Do you have any suggestions how else we can fix this ? Thanks in advance.

**Comment by uerceg** [comment] 2016-03-18 11:12
Hi @hovox 

Thanks for the report. Interesting thing. Is there a way for you to check if this issue is happening on jailbroken devices only?

**Comment by hovox** [comment] 2016-03-18 13:04
[Here is all information we have](http://crashes.to/s/0019fcedbba)

I'm supposing that this happening only on jailbroken devices because Crashlytics can't(I suppose) precisely detect is device jailbroken.

**Comment by uerceg** [comment] 2016-03-18 13:11
Thanks for the report, we'll start to investigate this thing. Will let you know as soon as I have some update on this issue.

**Comment by uerceg** [comment] 2018-08-15 12:45
Closing this issue since we were never able to reproduce it, but please feel free to open it in case you still face it with latest SDK version.

**Closed by uerceg** 2018-08-15 12:45 UTC
Labels: support
