### ISSUE TITLE
Delegate Callbacks in SDK

### ISSUE THREAD

**Issue by kfayzullin** [adjust/ios_sdk#86] opened 2015-03-20 10:01 UTC
We are missing the ability to receive callbacks client-side on 
- session
- install and 
- reattribution events

in the SDK version 4.x.

We need these to be able to sync adjust.io with other tracking tools client-side. 

We need the same information as the one which was available in SDK version 3.x, i.e.:

    - AIActivityKind activityKind indicates what kind of activity was tracked. It has one of these values:
         (AIActivityKindSession, AIActivityKindEvent, AIActivityKindRevenue, AIActivityKindReattribution)
    - NSString trackerToken the tracker token of the current install.
    - NSString trackerName the tracker name of the current install.
    - NSString network the network grouping level of the current install.
    - NSString campaign the campaign grouping level of the current install.
    - NSString adgroup the ad group grouping level of the current install.
    - NSString creative the creative grouping level of the current install.

**Comment by wellle** [comment] 2015-03-20 10:13
Duplicate of https://github.com/adjust/android_sdk/issues/92, lets continue the discussion over there.

**Comment by wellle** [comment] 2015-03-23 09:31
We will consider adding a second callback for SDK version 4.1 that gets executed every time an install, session, reattribution or event got successfully tracked.

**Comment by uerceg** [comment] 2016-03-15 17:16
And it's live officially now as part of newest version `4.6.0`. https://github.com/adjust/ios_sdk/releases/tag/v4.6.0

**Closed by uerceg** 2016-03-15 17:16 UTC
