### ISSUE TITLE
Crash, SDK 4.33.0, iOS 16.1.0, unrecognized selector +[SKAdNetwork updatePostbackConversionValue:coarseValue:lockWindow:completionHandler:]

### ISSUE THREAD

**Issue by eugeneego** [adjust/ios_sdk#641] opened 2022-11-28 08:59 UTC
We are expepiencing many crashes after updating to 4.33.0 on iOS 16.1.0.
4.32.1 works fine.

Adjust iOS SDK 4.33.0
iOS 16.1.0

```
Fatal Exception: NSInvalidArgumentException
+[SKAdNetwork updatePostbackConversionValue:coarseValue:lockWindow:completionHandler:]: unrecognized selector sent to class 0x22ba86d70

0  CoreFoundation                 0xa2c8
1  libobjc.A.dylib                0x17a68
2  CoreFoundation                 0x17e8b0
3  CoreFoundation                 0x203e0
4  CoreFoundation                 0x88790
5  AdjustSdk                      0x2f554 -[ADJSKAdNetwork updatePostbackConversionValue:coarseValue:lockWindow:completionHandler:]
6  AdjustSdk                      0x2f75c -[ADJSKAdNetwork adjUpdateConversionValue:coarseValue:lockWindow:completionHandler:]
7  AdjustSdk                      0x15ed0 -[ADJActivityHandler checkConversionValue:]
8  AdjustSdk                      0xab9c -[ADJActivityHandler finishedTracking:]
9  AdjustSdk                      0x24664 -[ADJPackageHandler sendNextPackage:]
10 AdjustSdk                      0x245bc -[ADJPackageHandler responseCallback:]
11 AdjustSdk                      0x26c48 __73-[ADJRequestHandler sendNSURLSessionRequest:responseData:methodTypeInfo:]_block_invoke
12 CFNetwork                      0x20544
13 CFNetwork                      0x30498
14 libdispatch.dylib              0x24b4
15 libdispatch.dylib              0x3fdc
16 libdispatch.dylib              0xb694
17 libdispatch.dylib              0xc214
18 libdispatch.dylib              0x16e10
19 libsystem_pthread.dylib        0xdf8
20 libsystem_pthread.dylib        0xb98
```

**Comment by Aditi3** [comment] 2022-11-28 13:43
Hi @eugeneego 

We've tried to reproduce the crash on our end but haven't been able to. Are you able to reproduce this yourself? If yes, do let us know the steps to reproduce the same.

Additionally, could you confirm if the crashes are happening on the iOS platform and not on macOS, watchOS, and tvOS?

**Comment by Dede** [comment] 2022-12-01 09:38
Hi, we are also starting to see same crash in new version of our iOS App with similar stack trace. We also couldn't reproduce it yet.

As far as I can see from beginning of the phased release, it seems it's only happening on iOS 16.1.0

**Comment by uerceg** [comment] 2022-12-01 19:37
@eugeneego @Dede Just to double check, do you guys have `StoreKit.framework` linked to your app?

**Comment by akbashev** [comment] 2022-12-04 07:34
Also seen an issue. So far just one user, iOS 16.1.0, iPhone 11. Adjust sdk version 4.32.1. We don’t have StoreKit linked to our app.

**Comment by eugeneego** [comment] 2022-12-05 10:07
> @eugeneego @Dede Just to double check, do you guys have `StoreKit.framework` linked to your app?

Yes, our app is linked to `StoreKit`.
The crash is only on iOS 16.1.0, no crashes on iOS 16.1.1. Probably it could be an iOS issue with new API availability that fixed in 16.1.1.

**Comment by eugeneego** [comment] 2022-12-05 17:15
@uerceg As I see in our analytics, we have minor audience on iOS 16.1.0, and we've released fix with reverting SDK to 4.32.1 quickly, so can't really tell about it's affected our entire iOS 16.1.0 user base.

**Comment by Dede** [comment] 2022-12-05 17:24
> Maybe one more question - do you see these crashes happening for your entire iOS 16.1.0 user base or just some of the users with that specific iOS version?

@uerceg it's only happening to a small amount of iOS 16.1.0 users. Our Adjust SDK version was 4.33.0 in that release.

**Comment by uerceg** [comment] 2023-02-09 12:38
Closing this one for now, but in case you still see the issue happening post this SDK update, please let us know and feel free to comment / reopen. Cheers.

**Closed by uerceg** 2023-02-09 12:38 UTC
