### ISSUE TITLE
Delay link response callback always after user click the notification authorize

### ISSUE THREAD

**Issue by KClichen** [adjust/ios_sdk#482] opened 2020-11-20 03:19 UTC
Delay link response callback always after user click the notification authorize.
I can't understand why not create a new thread to callback let me get the response result faster.

**Comment by uerceg** [comment] 2020-12-28 12:09
Duplicate of https://github.com/adjust/ios_sdk/issues/464.

**Closed by uerceg** 2020-12-28 12:09 UTC
