### ISSUE TITLE
Support for Simulators on M1 Macs

### ISSUE THREAD

**Issue by haib3rl** [adjust/ios_sdk#661] opened 2023-04-03 11:04 UTC
Xcode 14.3 dropped Support for Rosetta. Therefore we need the Support for Building for iOS Simulator on Apple Silicon Machines.  As we Use the Criteo Plugin It would be great if the Criteo would be enabled to run on Apple Silicon Devices without Rosetta.

See https://developer.apple.com/documentation/xcode/creating-a-multi-platform-binary-framework-bundle

**Comment by genadyb** [comment] 2023-04-04 08:39
Hello, @haib3rl.
Thank you for reaching out.
Could you please elaborate a little more on what is the problem?
How do you consume Adjust SDK with Criteo plugin, what is your building process and what the problem you are currently facing.
We will try to help you as soon as possible.
Thank you.

**Comment by haib3rl** [comment] 2023-04-06 07:41
Thanks for your Response. 

First of all we found a Workaround https://developer.apple.com/forums/thread/725563?answerId=749474022#749474022.
Apple Suggestions in [Technote3117](https://developer.apple.com/forums/thread/725563?answerId=749474022#749474022) didn't work out for us. As we don't know when Apple drops the Rosetta support for the Simulator it would be great if you could fix the following Error. 

"adjust Building for iOS Simulator, but linking in dylib built for iOS, file 'or architecture arm64"

Also simulators emulated with Rosetta aren't as performant as native arm64 Simulators. So we would really appreciate if you could add the support for "arm64-apple-ios-simulator"

**Comment by genadyb** [comment] 2023-04-21 21:47
Hello, @haib3rl.
Sorry for a delayed response.
Unfortunately we cannot reproduce your issue.
Could you guide us step-by-step to reproduce the error you are mentioning here, please?

**Comment by haib3rl** [comment] 2023-05-02 05:58
Issue was related to an outdated AdjustSignature at our Site

**Comment by genadyb** [comment] 2023-05-02 08:00
Thank you for the update.
You are welcome.
I'm closing the issue for now.

**Closed by genadyb** 2023-05-02 08:00 UTC
