### ISSUE TITLE
version 4.15.0 ADJActivityPackage.m line 96 -[ADJActivityPackage encodeWithCoder:] crash

### ISSUE THREAD

**Issue by wangjunhua1** [adjust/ios_sdk#353] opened 2018-10-31 10:09 UTC

**Comment by wangjunhua1** [comment] 2018-10-31 10:09
crash information :  <img width="806" alt="image" src="https://user-images.githubusercontent.com/11474284/47781196-17159e80-dd38-11e8-90a6-262b86d3f5be.png">

**Comment by wangjunhua1** [comment] 2018-10-31 10:10
device information  <img width="728" alt="image" src="https://user-images.githubusercontent.com/11474284/47781224-2bf23200-dd38-11e8-85fe-19a2f6959b8a.png">

**Comment by wangjunhua1** [comment] 2018-10-31 10:11
<img width="662" alt="image" src="https://user-images.githubusercontent.com/11474284/47781296-593ee000-dd38-11e8-9417-71928cad6299.png">

**Comment by nonelse** [comment] 2018-10-31 12:43
@wangjunhua1 thanks for the error report. 
Is this something that you are able to reproduce?
I will try to pressure the serialization mechanism to see if I see the same but having a reproducible scenario would help narrow it down.

**Comment by ondermerol** [comment] 2019-01-18 12:40
We have also the same crash problem and can not reproduce it. Can it be due to the reason like different threads using the same parameter?

**Comment by nonelse** [comment] 2019-01-28 15:55
I've looked at the code diff from [v4.14.1 to 4.15.0](https://github.com/adjust/ios_sdk/compare/e207090e...d746f718) and did not find anything related with reading or writing the [activity package array in the Package Handler](https://github.com/adjust/ios_sdk/blob/master/Adjust/ADJPackageHandler.m#L27).

There was a comment about the method [encodeWithCoder from ADJActivityPackage](https://github.com/adjust/ios_sdk/blob/master/Adjust/ADJActivityPackage.m#L89) being accessed from multiple threads and that causing this issue.
We do use a common to [function](https://github.com/adjust/ios_sdk/blob/master/Adjust/ADJUtil.m#L346) to serialize objects in files, but this function is static and does not have a state.
The file in [question](https://github.com/adjust/ios_sdk/blob/master/Adjust/ADJPackageHandler.m#L293) is only serialized from one [function](https://github.com/adjust/ios_sdk/blob/master/Adjust/ADJPackageHandler.m#L287). And that function is only called from functions that execute in the same [serial dispatch queue](https://github.com/adjust/ios_sdk/blob/master/Adjust/ADJPackageHandler.m#L52). One of the uses of a serial dispatch queue is to synchronize access to a specific resource and that is one the reasons that we use it.
We have been using this method since the beginning of the sdk and it has not changed in v4.15.0.

I've been looking at clues in the stack trace and found some candidate [here](https://forums.developer.apple.com/thread/63546#thread-post-193015) but that is not common to all stack traces, only the file write...

I've been trying to reproduce the crash, by artificially increasing the writing done in that file, but still can't see it.

I know that is unlikely but is there something done within the app regarding local files? Listing files, moving files and so on.

**Comment by ondermerol** [comment] 2019-01-30 08:05
No we haven't made any changes on the local files. We still couldn't reproduce the crash. There is another important information that it occurs in iOS 11 versions only (nearly half of them belongs to iOS 11.4.1).

**Comment by mqlsq** [comment] 2019-05-10 01:17
We have also the same crash problem in v4.14.1 .Have you solved the crash? @nonelse

**Comment by uerceg** [comment] 2020-03-20 22:27
Hey guys. 

Thanks for patience on this one. We have just released an [update](https://github.com/adjust/ios_sdk/releases/tag/v4.21.0) where we have replaced deprecated API which might be the source of these issues. If you can please give it a shot and let us know if crashes are still there with latest version or not, would be great to hear.

Cheers

**Comment by uerceg** [comment] 2020-04-09 11:55
Closing this one and moving discussion to https://github.com/adjust/ios_sdk/issues/350.

**Closed by uerceg** 2020-04-09 11:55 UTC
