### ISSUE TITLE
iOS 10, app.adjust.com deeplinks open app store even if app is installed

### ISSUE THREAD

**Issue by peacemoon** [adjust/ios_sdk#259] opened 2016-12-01 17:18 UTC
We use adjust sdk v.4.10.3 in our app.

I run adjust in `sandbox` enviroment

In application:continueUserActivity, I implemented Adjust.appWillOpenUrl like sample app.
````
    func application(application: UIApplication, continueUserActivity userActivity: NSUserActivity, restorationHandler: ([AnyObject]?) -> Void) -> Bool {
        if userActivity.activityType == NSUserActivityTypeBrowsingWeb {
            guard let url = userActivity.webpageURL else {
                return false
            }
            Adjust.appWillOpenUrl(url)

            guard let deepLinkUrl = url.embeddedAdjustDeepLinkURL(appManager.deepLinkManager.scheme) else {
                return false
            }

            appManager.openURL(deepLinkUrl)
        }

        return true
    }
````

When I click on a link https://app.adjust.com/w9342_tzsz22?deep_link=myscheme%3A%2F%2Fshopping%2Fazlist , I see different behaviour between iOS 9 & iOS 10.

In iOS9:
in application:continueUserActivity, the app received universal link in short form (https://21tz.adj.st/....) , and I can extract the deeplink from that link.

in iOS10:
in application:continueUserActivity, the app received first short universal link (https://21tz.adj.st/....) and I again can extract deeplink from universal link. But short time later, the app received again an old long universal link (https://reb0753472fc565462csub187765464f.ulink.adjust.com/ulink/shopping/detail/12345?excid=12345&adjust_reftag=xxxx&adjust_t=w9342&adjust_iredirect=https%3A%2F%2Fitunes.apple.com%2Fapp%2Fidxxxx%3Fmt%3D8&adjust_notrack=1) and app store is opened. 

I have checked my app and nowhere in my app can open app store.

It's really helpful if anyone can take a look and helps me debug this.

Thank you

**Comment by peacemoon** [comment] 2016-12-02 13:47
Today I remove the long adjust applinks from "Associated Domains", that means my app can only hanlde short adjust applinks. I try to open some https://app.adjust.com/12afde?deeplink=xxxx again, the app will always be opened. But "sometimes" the app store is also opened afterward :(

**Comment by uerceg** [comment] 2016-12-02 13:58
Hi @peacemoon 

So, at this moment, you have your app set up to handle short universal links, aka https://hash.adj.st/etc. I also assume that you have entered `xxxx` scheme from the upper link example to the adjust dashboard in place of universal links setup.

Lemme just check if I understood your properly: With this setup, after you click on the URL from above (https://app.adjust.com/12afde?deeplink=xxxx) your app gets opened, but sometimes app store as well?

If yes, how is this reflected (the store opening)? Is the App Store app being opened over your app or how?

**Comment by peacemoon** [comment] 2016-12-02 14:02
yes, my app is opened, the myappscheme://subview deeplink  is recognized correctly. And sometimes, the appstore is opened over my app. But only sometimes, not always.

**Comment by peacemoon** [comment] 2016-12-02 14:10
One more addition, this behaviour happens only on iOS 10 (I test on 2 devices with iOS 10.0.2 & 10.1.1). The ratio appstore open vs not open is about 40:60
On iOS 9, the appstore is **not** opened (I just test the same app on a deivce with iOS 9.3.5, click 10 times on same https://app.adjust.com/12afde?deeplink=xxxx link, and appstore is never opened.

**Comment by uerceg** [comment] 2016-12-02 14:11
Thank you for all of these infos, we will investigate if we can reproduce this behaviour and let you know ASAP.

**Comment by uerceg** [comment] 2016-12-02 18:33
I wasn't able to reproduce this issue unfortunately.

One thing from above draws my attention a bit. Can you explain me a bit what does this method in your code do?

```swift
appManager.openURL(deepLinkUrl)
```

If I need to guess by name of the method, seems to me like that you're trying to open the thing you're getting as a deep link, which in case of universal link is not your app custom URL scheme prefixed, but rather has `https` scheme. If you are maybe trying to launch that from this method, maybe Safari gets launched and our backend redirects to the store which causes App Store app to be opened. Not sure if this is happening, but would like to hear what are you doing with the URL inside of this method.

Cheers

**Comment by peacemoon** [comment] 2016-12-05 09:29
@uerceg Thank you for detail answer.

The appManager.openURL just perform `UIApplication.shareApplication().openURL()` on our custom URL scheme.

I added some print logs for you:
````
guard let url = userActivity.webpageURL else {
    return false
}

Debug.print("[continueUserActivity] url = \(url.absoluteString)")

Adjust.appWillOpenUrl(url)

guard let deepLinkUrl = url.embeddedAdjustDeepLinkURL(deepLinkManager.scheme) else {
    return false
}

Debug.print("[continueUserActivity] deepLinkUrl = \(deepLinkUrl.absoluteString)")

appManager.openURL(deepLinkUrl)
````

And this is the output when I click on the link: https://app.adjust.com/i9vt92_r5sz1h?deep_link=pbmobil%3A%2F%2Fshopping%2Fazlist 

````
[continueUserActivity] url = Optional("https://97ll.adj.st/shopping/azlist?adjust_reftag=cslRTmxCQa06b&adjust_t=i9vt92&adjust_iredirect=https%3A%2F%2Fitunes.apple.com%2Fapp%2Fid363126964%3Fmt%3D8&adjust_notrack=1")
[continueUserActivity] deepLinkUrl = Optional("pbmobil://shopping/azlist")
````

**Comment by peacemoon** [comment] 2016-12-05 09:59
One more thing:
when I comment out `Adjust.appWillOpenUrl(url)`, the app store is always opened.

**Comment by uerceg** [comment] 2016-12-05 10:02
Can you try commenting out the

```swift
appManager.openURL(deepLinkUrl)
```

line and let me know if app store ever got open after that?

**Comment by ihorzabrotsky** [comment] 2016-12-05 10:05
Guys, I am encountering the same problem with randomly moving to AppStore.
Besides that I want to ask you about Adjust's
`+ (NSURL *)convertUniversalLink:(NSURL *)url scheme:(NSString *)scheme`
method. How the "scheme" should look like? Can you provide some example?
Thanks in advance.

**Comment by peacemoon** [comment] 2016-12-05 10:14
@uerceg I tried to remove `appManager.openURL` , and the app store is still `sometimes` (not always) opened :(

If I commented out `Adjust.appWillOpenUrl(url)`, app store is always opened.

One more notice: If i click directly on universal link https://97ll.adj.st/shopping/azlist?adjust_reftag=cslRTmxCQa06b&adjust_t=i9vt92&adjust_iredirect=https%3A%2F%2Fitunes.apple.com%2Fapp%2Fid363126964%3Fmt%3D8&adjust_notrack=1 , app store is never opened

**Comment by uerceg** [comment] 2016-12-05 10:40
@ihorzabrotsky Thanks for reporting. `schemeName` is pretty much intended for you to put your `custom URL scheme` in there which you are using for your app. From your tracker URL example, that would pretty much be `myapp`. Can I ask you which iOS version does your device have in which you're seeing this? Are you able to reproduce this also while testing in sandbox mode?

@peacemoon Thank you for observations, we're investigating this, will ping you as soon as I have some news.

**Comment by ihorzabrotsky** [comment] 2016-12-05 10:52
@uerceg Thanks for the quick reply!
Currently I'm testing this on iPhone 5c with iOS 9.3.5 and on iPhone 7 with iOS 10.0.2. The situation is pretty the same on both devices.
I also wanted to specify one thing concerning the link: I receive Adjust-link from server and it looks like [myapp.com/x/xxxx](url) and when I want to convert this link I get an error "Url doesn't match as universal link or short version". So, does this link looks like the one I don't need? Does the only 2 types of links are:

**Comment by peacemoon** [comment] 2016-12-05 11:05
@ihorzabrotsky It looks like you have a different problem than mine. Would you mind to open a separated issue so that this issue stays cleaner. Thank you.

**Comment by uerceg** [comment] 2016-12-06 12:56
Okay, we investigated this thing on our side with backend team. Indeed, we have managed to reproduce this behaviour which you encountered @peacemoon. As far as we see, this seems like an iOS/Safari issue. Even w/o our SDK inside the app, same thing happens sporadically like you have experienced it.

If you are using tracker URL which looks like https://app.adjust.com/abc123?etc, when it comes to iOS 9 and above devices, redirection to the universal link will happen and seems that for some reason Safari/iOS 10 are not handling those things well in random cases.

If you are using directly the universal link (https://abcd.adj.st/etc), this issue does not occur.

This is pretty much it. Unfortunately, seems like some kind of an issue in how iOS 10/Safari are handling these things which weren't present on previous iOS versions.

We'll keep our eye on this issue and see if it can be solved somehow in the future, but as far as SDK is concerned -> it is not an SDK issue. Thus closing it, but feel free to ask in here if you have anything else you would like to know.

Cheers

**Closed by uerceg** 2016-12-06 12:56 UTC

**Comment by peacemoon** [comment] 2016-12-07 08:24
@uerceg just want to confirm that it seems to be a bug in Safari/iOS 10. I just check the link  https://app.adjust.com/abc123?etc in Chrome for iOS and the app store is never opened. It's really frustrating bug. Hopefully Apple will fix the bug soon.

**Comment by uerceg** [comment] 2016-12-07 08:27
Feel free to try it in Chrome. I was testing it from Chrome with the link in that format, from around 30 launches, I not a single time was the App Store app opened. Chrome doesn't seem to have this issue.
