### ISSUE TITLE
Pod won't install.

### ISSUE THREAD

**Issue by lukecharman** [adjust/ios_sdk#135] opened 2015-10-28 16:09 UTC
`CocoaPods 0.39.0 is available.
To update use: `gem install cocoapods`
Until we reach version 1.0 the features of CocoaPods can and will change.
We strongly recommend that you use the latest version at all times.

For more information see http://blog.cocoapods.org
and the CHANGELOG for this version http://git.io/BaH8pQ.

Analyzing dependencies
Pre-downloading: `Adjust` from `git://github.com/adjust/ios_sdk.git`, tag `v4.4.1`
[!] Unable to find a specification for 'Adjust'.

[!] Unable to load a podspec from `Adjust.podspec`, skipping:

Pod::DSLError`

**Comment by uerceg** [comment] 2015-10-28 16:23
Hi @lukecharman 

I have just checked and I successfully added Adjust pod to XCode project. Here's the log output:

```
adjust:AdjustPod uerceg$ pod install
Updating local specs repositories
Analyzing dependencies
Pre-downloading: `Adjust` from `git://github.com/adjust/ios_sdk.git`, tag `v4.4.1`
Downloading dependencies
Installing Adjust (4.4.1)
Generating Pods project
Integrating client project

[!] Please close any current Xcode sessions and use `AdjustPod.xcworkspace` for this project from now on.
Sending stats
Pod installation complete! There is 1 dependency from the Podfile and 1 total pod installed.
```

My pod version:

```
adjust:AdjustPod uerceg$ pod --version
0.39.0
```

My `Podfile`:

```
platform :ios, '5.0'

target 'AdjustPod' do

pod 'Adjust', :git => 'git://github.com/adjust/ios_sdk.git', :tag => 'v4.4.1'

end
```

Maybe you should update CocoaPods to 0.39.0 and then give it a try?

**Comment by uerceg** [comment] 2015-11-17 08:04
@lukecharman Any luck with this issue?

**Comment by baoluo** [comment] 2015-12-01 16:28
I have the same issue, running cocoa pods v0.38

**Comment by uerceg** [comment] 2015-12-01 16:46
@baoluo I am now repeating the same question like above, but would it be possible to try with latest `cocoapods 0.39.0`? We have tested our pod and its installation and everything worked just fine, we can't reproduce any error while installing it.

**Comment by baoluo** [comment] 2015-12-01 16:48
@uerceg, it might work with the latest cocoa pods version, but unfortunately we can't install it for the moment, maybe in few months due to others incompatibilities.

**Comment by uerceg** [comment] 2015-12-01 17:08
@baoluo I see. Can you maybe just paste me in here error output you're getting once trying to install with 0.38? I'll check if I can reproduce the issue.

**Comment by baoluo** [comment] 2015-12-02 09:41
@uerceg Thank you, actually it's exactly the same output as @lukecharman

**Comment by kiluag** [comment] 2015-12-03 08:23
2015.12.3 
 pod version：0.39.0
same issue

**Comment by uerceg** [comment] 2015-12-09 16:19
I managed to reproduce this issue with `0.38.0`, but we are unsure what is causing this issue. We tried it on several machines and upgrading CocoaPods from `0.38.0` to `0.39.0` solved the issue.

**Comment by bsuvorov** [comment] 2015-12-27 06:47
@uerceg , I'm having same issue on 0.38.2.
Upgrading to 0.39.0 is not an option at the moment, since there are regressions that would need to be resolved, but integrating adjust is important.

Have you considered adding Adjust to main trunk? 
https://guides.cocoapods.org/making/getting-setup-with-trunk.html

I wonder if it would resolve the issue.
So currently, the way to add Adjust is  with this line:
 pod 'Adjust', :git => 'git://github.com/adjust/ios_sdk.git', :tag => 'v4.5.0'

By adding it to the main trunk, developers should be able to do following:
 pod 'Adjust', 'v4.5.0'

and "pod install" might as well simply find the spec.

**Comment by uerceg** [comment] 2015-12-27 14:42
@bsuvorov Thanks for the report and also for the advice. We will test the solution and update you on this issue as soon as possible.

**Comment by uerceg** [comment] 2015-12-28 09:34
@bsuvorov Did you maybe try by adding following line to your `Podfile`:

```
pod 'Adjust', '~> 4.5.0'
```

Again, I managed to install it on my machine with it as well.

**Comment by bsuvorov** [comment] 2015-12-30 22:35
ooooh, so now it is obvious what's going on

so we need to drop "v" from the tag to make it work.

Here is what happens for everyone on this thread who had issue.
Everyone goes to adjust ios_sdk instructions and copies this line into podfile:
pod 'Adjust', :git => 'git://github.com/adjust/ios_sdk.git', :tag => 'v4.5.0'

it fails on cocoa pods < 0.39

if we try delete everything necessary we end up with
pod 'Adjust', 'v4.5.0' 

But it also fails and complains on malformed tag version.

So if we drop 'v' from the tag, then everything just magically works as expected.

**Comment by uerceg** [comment] 2015-12-31 00:34
Interesting catch. Thanks for the update. @lukecharman @baoluo If you can test this solution suggested above, it would be great to hear feedback.

**Comment by lukecharman** [comment] 2016-01-20 13:21
Mm, it's working for me with the standard podfile syntax, no need for the custom repo URL.

**Comment by uerceg** [comment] 2016-03-03 09:49
Should now be fixed with these instructions: https://github.com/adjust/ios_sdk/pull/174 and https://github.com/adjust/ios_sdk/pull/176.

**Closed by uerceg** 2016-03-03 09:49 UTC
