### ISSUE TITLE
Crash: 4.35.3 [ADJActivityPackage encodeWithCoder:] ADJActivityPackage.m:92

### ISSUE THREAD

**Issue by AttiaMo** [adjust/ios_sdk#690] opened 2023-12-06 15:36 UTC
Hi 

Crashlytics is reporting a crash coming from the Adjust sdk.

### Environment

- SDK Version: [Adjust SDK `4.35.3` ]
- iOS Version: [All]
- Installation Method: [SPM]

### Crash logs

```
Crashed: io.adjust.PackageQueue
0  libobjc.A.dylib                0x346c objc_retain_x0 + 16
1  libobjc.A.dylib                0x346c objc_retain + 16
2  Foundation                     0x159cc -[NSDictionary(NSDictionary) encodeWithCoder:] + 480
3  Foundation                     0x125d0 _encodeObject + 1096
4  Vestiaire Collective           0xe502a0 -[ADJActivityPackage encodeWithCoder:] + 92 (ADJActivityPackage.m:92)
5  Foundation                     0x125d0 _encodeObject + 1096
6  Foundation                     0x547a4 -[NSKeyedArchiver _encodeArrayOfObjects:forKey:] + 344
7  Foundation                     0x125d0 _encodeObject + 1096
8  Foundation                     0x2a97c +[NSKeyedArchiver archivedDataWithRootObject:requiringSecureCoding:error:] + 88
9  Vestiaire Collective           0xe70e7c +[ADJUtil writeObject:fileName:objectName:syncObject:] + 334 (ADJUtil.m:334)
10 Vestiaire Collective           0xe64d78 -[ADJPackageHandler writePackageQueueS:] + 349 (ADJPackageHandler.m:349)
11 Vestiaire Collective           0xe642b0 -[ADJPackageHandler addI:package:] + 219 (ADJPackageHandler.m:219)
12 Vestiaire Collective           0xe73038 __42+[ADJUtil launchInQueue:selfInject:block:]_block_invoke + 804 (ADJUtil.m:804)
13 libdispatch.dylib              0x637a8 _dispatch_call_block_and_release + 24
14 libdispatch.dylib              0x64780 _dispatch_client_callout + 16
15 libdispatch.dylib              0x3f6fc _dispatch_lane_serial_drain$VARIANT$armv81 + 600
16 libdispatch.dylib              0x401b0 _dispatch_lane_invoke$VARIANT$armv81 + 380
17 libdispatch.dylib              0x49f14 _dispatch_workloop_worker_thread + 608
18 libsystem_pthread.dylib        0x1bd0 _pthread_wqthread + 284
19 libsystem_pthread.dylib        0x1720 start_wqthread + 8
```
### Steps to Reproduce

- No luck to reproduce but it happens for 10 users minmum a day 

Any Idea how to fix?

**Comment by victor-yn** [comment] 2023-12-11 12:54
@Aditi3 @uerceg Hey, could you have a look at this? 🙏

We had to revert back to **4.33.3** due to this crash impacting our app stability after upgrading to **4.35.3**. We were not seeing this crash on **4.33.3**. Let us know if you need more information.

**Comment by AttiaMo** [comment] 2023-12-14 15:11
hi @uerceg For us `4.33.3` was completely fine, so we had to revert to it.

Thank you

**Comment by uerceg** [comment] 2023-12-14 15:19
Hi @AttiaMo,

Thank you for the info. During your usage of 4.35.3 - did you maybe use [ATT delay feature](https://github.com/adjust/ios_sdk/blob/54096650288c5c4411a24c5594e28f033a77aff7/Adjust/ADJConfig.h#L189)?

**Comment by AttiaMo** [comment] 2023-12-14 15:31
Yeah, it was just upgrading the SDK, nothing changed from our side.

**Comment by jc-paris** [comment] 2023-12-14 16:04
FYI, we have the same issue with v4.35.2

**Comment by genadyb** [comment] 2023-12-19 15:29
Thank you for your inputs.

We are trying to reproduce this crash, but with no success for now.
We will continue to look into that issue, but it might take some time, though, due to a Holliday period.

In case it is possible, please use 4.33.3, until we figure out the root cause of this crash and fix it in the upcoming release.

**Comment by jc-paris** [comment] 2024-01-10 08:09
Hello @genadyb @uerceg,

Any news on the matter ? This crash is still our top 3 and so impacting many users in our app.

**Comment by victor-yn** [comment] 2024-03-20 09:33
Hey @genadyb @uerceg,

Do we have any news about this? We're unfortunately stuck at `4.33.3` for now as suggested above due to this crash

**Comment by genadyb** [comment] 2024-03-22 13:44
Hello, @AttiaMo, @victor-yn, @jc-paris.

Thank you for the reporting and monitoring this issue.
Unfortunately, we still cannot reproduce this issue on our end.
In order to try reproducing this crash I would like to ask you to provide the following information:

1. `Integrated Adjust SDK version number` (where the crash is happening). We are aware of this issue happening in 4.35.2 / 4.35.3, please let us know if you experience such crashes in any other Adjust SDK version too.
2. `Integration type` - Cocoapods / SPM / Pre-built framework (what type) / etc.
3. `Application development language` - Swift or ObjC?
4. `Statistics about iOS versions where the crash happens` - percentage of crashes per iOS version. This way we would like to see the distribution and severity of crashed among the different iOS versions.
5. `Full crash reports for these crashes` - it would be great to receive as many such full crash reports as possible while stating the related Adjust SDK version.
6. `Adjust Configuration` you're initializing the Adjust SDK with and what Adjust APIs are you using in your code.
7. Are you using a `Adjust Signature plugin` next to the Adjust SDK?
8. Are you using a Purchase Verification API, i.e. 
`+ (void)verifyPurchase:(nonnull ADJPurchase *)purchase completionHandler:(void (^_Nonnull)(ADJPurchaseVerificationResult * _Nonnull verificationResult))completionHandler; `
?

Thank you for the cooperation.
We will try our best to fix this issue as soon as possible with your help.

**Comment by efguydan** [comment] 2024-03-22 16:02
Hi @genadyb , Thanks for the reply. Coming back on this in place of @AttiaMo, I'll try to answer your questions as best as I can

1. We have faced the issue on `4.35.3` and most recently on `4.37.2`. Both  of these times, we reverted to `4.33.3` to mitigate the issue.
2. SPM
3. Swift
4. On Version `4.35.3`, we encountered this issue about 10 times a day as @AttiaMo has reported [here](https://github.com/adjust/ios_sdk/issues/690#issue-2028826342) while in `4.37.2`, we had 12 events in about 3 days but this time, we never reached full adoption before we rolled back to `4.33.3`
5. Here is the crash report from Firebase in the most recent crash we had
```
Crashed: io.adjust.PackageQueue
0  libobjc.A.dylib                0x1c20 objc_msgSend + 32
1  Foundation                     0x172d4 -[NSDictionary(NSDictionary) encodeWithCoder:] + 488
2  Foundation                     0x13b44 _encodeObject + 1188
3  Vestiaire Collective           0xe1cebc -[ADJActivityPackage encodeWithCoder:] + 92 (ADJActivityPackage.m:92)
4  Foundation                     0x13b44 _encodeObject + 1188
5  Foundation                     0x5a1ec -[NSKeyedArchiver _encodeArrayOfObjects:forKey:] + 468
6  Foundation                     0x5a6d0 -[NSArray(NSArray) encodeWithCoder:] + 588
7  Foundation                     0x13b44 _encodeObject + 1188
8  Foundation                     0x2d494 +[NSKeyedArchiver archivedDataWithRootObject:requiringSecureCoding:error:] + 92
9  Vestiaire Collective           0xe3df14 +[ADJUtil writeObject:fileName:objectName:syncObject:] + 334 (ADJUtil.m:334)
10 Vestiaire Collective           0xe31bd4 -[ADJPackageHandler writePackageQueueS:] + 350 (ADJPackageHandler.m:350)
11 Vestiaire Collective           0xe310c8 -[ADJPackageHandler addI:package:] + 219 (ADJPackageHandler.m:219)
12 Vestiaire Collective           0xe400a4 __42+[ADJUtil launchInQueue:selfInject:block:]_block_invoke + 804 (ADJUtil.m:804)
13 libdispatch.dylib              0x24b4 _dispatch_call_block_and_release + 32
14 libdispatch.dylib              0x3fdc _dispatch_client_callout + 20
15 libdispatch.dylib              0xb694 _dispatch_lane_serial_drain + 672
16 libdispatch.dylib              0xc1e0 _dispatch_lane_invoke + 384
17 libdispatch.dylib              0x16e10 _dispatch_workloop_worker_thread + 652
18 libsystem_pthread.dylib        0xdf8 _pthread_wqthread + 288
19 libsystem_pthread.dylib        0xb98 start_wqthread + 8
```
6. We have a basic Adjust Config setup. 
    - We set a log level
    - set a delegate to get deferred deeplinks when applicable
Here is a code snippet
```swift
let adjustConfig = ADJConfig(appToken: token, environment: environment)
adjustConfig?.logLevel = ADJLogLevelAssert
adjustConfig?.delegate = self
Adjust.addSessionPartnerParameter("key", value: value)
Adjust.appDidLaunch(adjustConfig)
```
In terms of the APIs we use, We mostly use the tracking APIs via 
    - Adjust.trackEvent
    - Adjust.trackThirdPartySharing
    - Adjust.appDidLaunch
    - Adjust.addSessionPartnerParameter
    - Adjust.appWillOpen
   and some others such as 
    - Adjust.convertUniversalLink
    - Adjust.setDeviceToken
7.  Yes. it is a plugin we drag & drop in the project, no additional configuration needed.
8. No we are not.

Thank you and I hope these information is helpful in your investigation.
Good luck!

**Comment by genadyb** [comment] 2024-03-22 17:08
Hi, @efguydan.
Thank you for such a quick answer.
- Regarding `4`. 
While it's very valuable information about the crashes per Adjust SDK version distribution, I would like to know about the iOS version on devices (and, if possible, models) that experienced these crashes.
- Regarding 5.
Is it possible to receive the full crash report from the Firebase, that includes all the running queues with their corresponding call stacks and other meta data and not only the crashed queue like you sent?
Thank you very much.

**Comment by efguydan** [comment] 2024-03-25 14:37
Hi @genadyb 

- The crash affects 70% iOS 17, 20% iOS 16 and 10% iOS 15, which aligns with our user iOS version spread. For their models,. there doesn't seem to be any thing that stands out. Check screenshot below.

<details open>
  <summary>Device Models</summary>

![image](https://github.com/adjust/ios_sdk/assets/17221356/1ac0a554-f3c7-47f9-a8db-0c5975484864)

</details>

- Yes of course, I will attach 5 metadata and full crash report from firebase below

<details open>
  <summary>MetaDatas</summary>

![image](https://github.com/adjust/ios_sdk/assets/17221356/02ff2587-a494-4fb2-9dc5-0dc9f6172367)

![Screenshot 2024-03-25 at 15 31 19](https://github.com/adjust/ios_sdk/assets/17221356/3e80477e-27d8-4fb1-bdea-d7e89268cbd6)

![Screenshot 2024-03-25 at 15 31 30](https://github.com/adjust/ios_sdk/assets/17221356/25490508-c830-450d-8fab-99981a31373a)

![Screenshot 2024-03-25 at 15 31 43](https://github.com/adjust/ios_sdk/assets/17221356/021f7ab9-adee-4f92-84b0-4d76f07b5a51)

![Screenshot 2024-03-25 at 15 31 52](https://github.com/adjust/ios_sdk/assets/17221356/d9e4d1a2-1cb8-41c3-8e77-5e54c9a26a19)

</details>

<details open>
  <summary>StackTraces</summary>

[ssue_75c303fcebc05a38b0edcfa17d1f5f74_crash_session_c09ab7ef77ee425a9a2f05a9c5ed721f_DNE_2_v2_stacktrace.txt](https://github.com/adjust/ios_sdk/files/14744914/ssue_75c303fcebc05a38b0edcfa17d1f5f74_crash_session_c09ab7ef77ee425a9a2f05a9c5ed721f_DNE_2_v2_stacktrace.txt)

[issue_75c303fcebc05a38b0edcfa17d1f5f74_crash_session_ea34dec932b4415391da42bc02672083_DNE_0_v2_stacktrace.txt](https://github.com/adjust/ios_sdk/files/14744915/issue_75c303fcebc05a38b0edcfa17d1f5f74_crash_session_ea34dec932b4415391da42bc02672083_DNE_0_v2_stacktrace.txt)

[issue_75c303fcebc05a38b0edcfa17d1f5f74_crash_session_273b97275b924ea2b932ec707bc147ed_DNE_0_v2_stacktrace.txt](https://github.com/adjust/ios_sdk/files/14744916/issue_75c303fcebc05a38b0edcfa17d1f5f74_crash_session_273b97275b924ea2b932ec707bc147ed_DNE_0_v2_stacktrace.txt)

[issue_75c303fcebc05a38b0edcfa17d1f5f74_crash_session_ca7d45d40b504153960c2f07338569b7_DNE_0_v2_stacktrace.txt](https://github.com/adjust/ios_sdk/files/14744917/issue_75c303fcebc05a38b0edcfa17d1f5f74_crash_session_ca7d45d40b504153960c2f07338569b7_DNE_0_v2_stacktrace.txt)

[issue_75c303fcebc05a38b0edcfa17d1f5f74_crash_session_53aefaacae6a4fc8b437ca9e54a4bdc0_DNE_0_v2_stacktrace.txt](https://github.com/adjust/ios_sdk/files/14744918/issue_75c303fcebc05a38b0edcfa17d1f5f74_crash_session_53aefaacae6a4fc8b437ca9e54a4bdc0_DNE_0_v2_stacktrace.txt)

</details>

Thanks and I hope it helps with your investigation 🙏🏽

**Comment by genadyb** [comment] 2024-03-25 16:17
Hi, @efguydan.
Thank you very much for your help.
I'm analysing the data you've provided and let you know about the results very soon.
🙏🏻

**Comment by genadyb** [comment] 2024-03-25 16:53
@efguydan 
I have a small question - what Adjust SDK version is integrated in your App's 5.164.0 (836)?
Thank you 🙏🏻

**Comment by efguydan** [comment] 2024-03-25 16:59
Hey @genadyb, in our version`5.164.0 (836)`, we had Adjust SDK version `4.37.2`.

**Comment by baldursson** [comment] 2024-04-02 10:24
Is downgrading to 4.33.3 still the only way to mitigate these crashes? It is now the most common crash reason in our app.

**Comment by genadyb** [comment] 2024-04-03 13:56
Hello @AttiaMo, @victor-yn, @jc-paris, @baldursson.
We've checked this crash root cause and it looks like we fixed it in our latest [4.38.0](https://github.com/adjust/ios_sdk/releases/tag/v4.38.0) release.
Could you please check this out and let us know whether the problem was fixed or not.
Many thanks for your priceless help and cooperation.

**Comment by genadyb** [comment] 2024-05-10 15:38
@AttiaMo @victor-yn @jc-paris @baldursson 
We are closing this issue for now.
Please feel free to reopen it if the issue is back again.

**Comment by efguydan** [comment] 2024-05-10 15:40
Hey @genadyb , Happy to report that we have been on the proposed version for a bit and the crash has not resurfaced.

Thanks a bunch for the fix 🙏🏽

**Comment by genadyb** [comment] 2024-05-31 14:32
Fixed and verified.

**Closed** 2024-05-31 14:32 UTC
