### ISSUE TITLE
Crash in adjUpdateConversionValue:coarseValue:lockWindow:completionHandler:

### ISSUE THREAD

**Issue by nburyak** [adjust/ios_sdk#647] opened 2022-12-28 20:28 UTC
Hi, we're using segment integration of the Adjust SDK and in the latest `v4.33.2` we started observing a crash on `adjUpdateConversionValue:coarseValue:lockWindow:completionHandler:` on tvOS. 

- OS: tvOS
- Adjust: v4.33.2
- Previously used Adjust Version (non-crashing): 4.32.1

It's not possible to reproduce the issue locally, I can only see it on Sentry. The issue has dropped down the crash-free rate to 86%

![image](https://user-images.githubusercontent.com/2462403/209868305-97a1d36e-722f-4936-a51d-ae6195797b76.png)

**Comment by uerceg** [comment] 2022-12-29 11:49
Hi @nburyak,

Thank you for reporting this. We have just shipped [iOS SDK v4.33.3](https://github.com/adjust/ios_sdk/releases/tag/v4.33.3) to try to address this issue. Let us know if that version fixed this issue for you.

**Comment by uerceg** [comment] 2023-02-01 00:15
Closing this for now, but feel free to reopen / comment in case the issue is still there even with latest SDK version. Cheers.

**Closed by uerceg** 2023-02-01 00:15 UTC
