### ISSUE TITLE
unable to see adidValue for reinstalling a device

### ISSUE THREAD

**Issue by shooshx** [adjust/ios_sdk#193] opened 2016-05-26 10:46 UTC
I'm trying for follow the instructions here:
https://github.com/adjust/ios_sdk#im-not-seeing-install-tracked-in-the-logs
on how to see "Install tracked"
The instructions reference an above answer
https://github.com/adjust/ios_sdk#forget-device
but to follow this I need the value of adidValue, which I don't have
I trying removing and re-running the app but I'm not seeing the mentioned "Session failed" error message. All I'm seeing is this:

```
2016-05-26 13:37:20.361 GatesOfWarIOS InHouse[454:16135] 	[Adjust]a: SANDBOX: Adjust is running in Sandbox mode. Use this setting for testing. Don't forget to set the environment to `production` before publishing
2016-05-26 13:37:20.362 GatesOfWarIOS InHouse[454:16135] 	[Adjust]v: Attribution file not found
2016-05-26 13:37:20.362 GatesOfWarIOS InHouse[454:16135] 	[Adjust]v: Activity state file not found
2016-05-26 13:37:20.363 GatesOfWarIOS InHouse[454:16135] 	[Adjust]v: Foreground timer fires after 60.0 seconds of starting and cycles every 60.0 seconds
2016-05-26 13:37:20.383 GatesOfWarIOS InHouse[454:16273] 	[Adjust]v: Package queue file not found
2016-05-26 13:37:20.390 GatesOfWarIOS InHouse[454:16272] 	[Adjust]d: iAd with 2 tries to read v3
2016-05-26 13:37:20.390 GatesOfWarIOS InHouse[454:16272] 	[Adjust]d: ADJUST_NO_IAD or TARGET_OS_TV not set
```

**Comment by uerceg** [comment] 2016-05-26 11:03
Hi @shooshx

If you are using SDK version 4.6.0 and above, you can set event tracking callback and you can access `adid` value in there. But in case that you are not doing this, you can try to track some event and in logs you will see you `IDFA` value which can also be used for forgetting your device.

For more info: https://docs.adjust.com/en/getting-started/#testing-attribution

And indeed, in our Github README we have written only method with `adid` and thank you for pointing this thing to us with this issue, we'll update the README. Thanks!

Let me know if this worked for you.

Cheers

**Comment by shooshx** [comment] 2016-05-26 11:52
I got the idfa using
`[[Adjust idfa] UTF8String]`
and tried using this like:
http://app.adjust.com/forget_device?app_token=XXXXX&idfa=65BB1915-82DE-4473-8461-47512A76814B
(app-token removed)
and I get a reply that confirmed it was removed
running the app again, I'm still not getting "Install tracked" in the log. just this:

```
2016-05-26 14:48:00.896 GatesOfWarIOS InHouse[913:39372] 	[Adjust]a: SANDBOX: Adjust is running in Sandbox mode. Use this setting for testing. Don't forget to set the environment to `production` before publishing
2016-05-26 14:48:00.897 GatesOfWarIOS InHouse[913:39372] 	[Adjust]v: Attribution file not found
2016-05-26 14:48:00.899 GatesOfWarIOS InHouse[913:39372] 	[Adjust]d: Read Activity state: ec:0 sc:1 ssc:4 ask:0 sl:4106.0 ts:2917.5 la:1464263154.2 dt:(null)
2016-05-26 14:48:00.900 GatesOfWarIOS InHouse[913:39372] 	[Adjust]v: Foreground timer fires after 60.0 seconds of starting and cycles every 60.0 seconds
2016-05-26 14:48:00.902 GatesOfWarIOS InHouse[913:39508] 	[Adjust]d: Package handler read 0 packages
2016-05-26 14:48:00.924 GatesOfWarIOS InHouse[913:39459] 	[Adjust]d: iAd with 2 tries to read v3
2016-05-26 14:48:00.924 GatesOfWarIOS InHouse[913:39459] 	[Adjust]d: ADJUST_NO_IAD or TARGET_OS_TV not set
```

**Comment by uerceg** [comment] 2016-05-26 11:58
But you didn't uninstall the app from your device, right? You have just re-run it from Xcode?

Flow should be:
1. Uninstall the app completely from the device.
2. Forget your device with forget URL.
3. Install and run the app on your device.

**Comment by shooshx** [comment] 2016-05-26 12:20
Thank you, that worked
It might also be worth mentioning in the README that the "Install tracked" does not appear immediately when calling [Adjust appDidLaunch:adjustConfig] but instead it takes some time (10 seconds in my case) and is called from a different thread.
(and if the app closes shortly after calling [Adjust appDidLaunch:adjustConfig] it might not have time to appear at all)

**Comment by uerceg** [comment] 2016-05-26 12:40
Great, glad it worked. I will close this issue, feel free to reopen it if you have any issues with this again.

And regarding `Install tracked` message...

Well, basically after calling `[Adjust appDidLaunch:adjustConfig]` what happens on first run is that the SDK is sending session package to our backend and first session package is installation. As soon as we get response to that package (and that should be pretty much instantly, and not after 10 seconds), we are printing out that install has been tracked.

Can you maybe paste me in here your logs from the time you start your app on your device for the first time together with line where you got `Install tracked` message?

**Closed by uerceg** 2016-05-26 12:40 UTC

**Comment by shooshx** [comment] 2016-05-26 12:57
8 seconds, my mistake
The relevant logs:

Startup -
```
2016-05-26 15:14:24.572 X[1099:50474] 	[Adjust]a: SANDBOX: Adjust is running in Sandbox mode. Use this setting for testing. Don't forget to set the environment to `production` before publishing
2016-05-26 15:14:24.573 XX[1099:50474] 	[Adjust]v: Attribution file not found
2016-05-26 15:14:24.573 XX[1099:50474] 	[Adjust]v: Activity state file not found
2016-05-26 15:14:24.575 XX[1099:50555] 	[Adjust]v: Package queue file not found
2016-05-26 15:14:24.576 XX[1099:50474] 	[Adjust]v: Foreground timer fires after 60.0 seconds of starting and cycles every 60.0 seconds
2016-05-26 15:14:24.577 XX[1099:50631] 	[Adjust]d: iAd with 2 tries to read v3
2016-05-26 15:14:24.577 XX[1099:50631] 	[Adjust]d: ADJUST_NO_IAD or TARGET_OS_TV not set
2016-05-26 15:14:24.621 XX[1099:50474] 	[Adjust]d: Adjust already enabled
```

After 8 seconds:

```
2016-05-26 15:14:32.157 XX[1099:50625] 	[Adjust]v: Background timer canceled
2016-05-26 15:14:32.157 XX[1099:50625] 	[Adjust]v: Foreground timer starting
2016-05-26 15:14:32.157 XX[1099:50625] 	[Adjust]v: Subsession start
2016-05-26 15:14:32.159 XX[1099:50652] 	[Adjust]d: Added package 1 (session)
2016-05-26 15:14:32.159 XX[1099:50652] 	[Adjust]v: Path:      /session
2016-05-26 15:14:32.159 XX[1099:50652] 	[Adjust]v: ClientSdk: ios4.7.0
2016-05-26 15:14:32.159 XX[1099:50652] 	[Adjust]v: Parameters:
2016-05-26 15:14:32.159 XX[1099:50652] 	[Adjust]v: 		app_token              gap1o5dzgjy8
2016-05-26 15:14:32.161 XX[1099:50625] 	[Adjust]d: Wrote Activity state: ec:0 sc:1 ssc:1 ask:0 sl:0.0 ts:0.0 la:1464264872.2 dt:(null)
2016-05-26 15:14:32.166 XX[1099:50652] 	[Adjust]v: 		app_version            0.0.000-develop-de56b9e0c9fd05ce4cfa8356cf1eadf6b2cc1357
2016-05-26 15:14:32.170 XX[1099:50652] 	[Adjust]v: 		app_version_short      0.0.000
2016-05-26 15:14:32.170 XX[1099:50652] 	[Adjust]v: 		bundle_id              com.plarium.games.XXX.tests
2016-05-26 15:14:32.170 XX[1099:50652] 	[Adjust]v: 		country                IL
2016-05-26 15:14:32.170 XX[1099:50652] 	[Adjust]v: 		cpu_type               CPU_SUBTYPE_ARM64_V8
2016-05-26 15:14:32.170 XX[1099:50652] 	[Adjust]v: 		created_at             2016-05-26T15:14:32.158Z+0300
2016-05-26 15:14:32.170 XX[1099:50652] 	[Adjust]v: 		device_name            iPad5,3
2016-05-26 15:14:32.171 XX[1099:50652] 	[Adjust]v: 		device_type            iPad
2016-05-26 15:14:32.171 XX[1099:50652] 	[Adjust]v: 		environment            sandbox
2016-05-26 15:14:32.172 XX[1099:50652] 	[Adjust]v: 		event_buffering_enabled 0
2016-05-26 15:14:32.172 XX[1099:50652] 	[Adjust]v: 		hardware_name          J81AP
2016-05-26 15:14:32.172 XX[1099:50652] 	[Adjust]v: 		idfa                   65BB1915-82DE-4473-8461-47512A76814B
2016-05-26 15:14:32.172 XX[1099:50652] 	[Adjust]v: 		idfv                   9A65D74E-2CBC-4FB2-97CE-89D38D7BB095
2016-05-26 15:14:32.172 XX[1099:50652] 	[Adjust]v: 		ios_uuid               819c515b-4313-4abb-b057-e5c8e1b9b042
2016-05-26 15:14:32.173 XX[1099:50652] 	[Adjust]v: 		language               en
2016-05-26 15:14:32.173 XX[1099:50652] 	[Adjust]v: 		needs_response_details 0
2016-05-26 15:14:32.173 XX[1099:50652] 	[Adjust]v: 		os_name                ios
2016-05-26 15:14:32.173 XX[1099:50652] 	[Adjust]v: 		os_version             9.3.2
2016-05-26 15:14:32.176 XX[1099:50652] 	[Adjust]v: 		session_count          1
2016-05-26 15:14:32.176 XX[1099:50652] 	[Adjust]v: 		tracking_enabled       1
2016-05-26 15:14:32.180 XX[1099:50652] 	[Adjust]d: Package handler wrote 1 packages

2016-05-26 15:14:32.505 XX[1099:50566] 	[Adjust]v: Response: {"attribution":{"tracker_token":"XX","tracker_name":"Organic","network":"Organic"},"app_token":"XX","adid":"97d7c555a644fca23b7dfbe0a5238c0b","timestamp":"2016-05-26T12:14:32.408Z+0000","message":"Install tracked","ask_in":5000}
2016-05-26 15:14:32.505 XX[1099:50566] 	[Adjust]i: Install tracked
2016-05-26 15:14:32.511 XX[1099:50566] 	[Adjust]d: Wrote Activity state: ec:0 sc:1 ssc:1 ask:1 sl:0.0 ts:0.0 la:1464264872.2 dt:(null)
2016-05-26 15:14:32.511 XX[1099:50566] 	[Adjust]d: Waiting to query attribution in 5000 milliseconds
2016-05-26 15:14:32.511 XX[1099:50566] 	[Adjust]v: Attribution timer starting. Launching in 5.0 seconds
2016-05-26 15:14:32.512 XX[1099:50625] 	[Adjust]d: Package handler wrote 0 packages

2016-05-26 15:14:32.778 XX[1099:50625] 	[Adjust]d: Added sdk_click 1
2016-05-26 15:14:32.778 XX[1099:50625] 	[Adjust]v: Path:      /sdk_click
2016-05-26 15:14:32.778 XX[1099:50625] 	[Adjust]v: ClientSdk: ios4.7.0
2016-05-26 15:14:32.778 XX[1099:50625] 	[Adjust]v: Parameters:
2016-05-26 15:14:32.778 XX[1099:50625] 	[Adjust]v: 		app_token              gap1o5dzgjy8
2016-05-26 15:14:32.778 XX[1099:50625] 	[Adjust]v: 		created_at             2016-05-26T15:14:32.778Z+0300
2016-05-26 15:14:32.778 XX[1099:50625] 	[Adjust]v: 		details                {"Version3.1":{"iad-lineitem-id":"1234567890","iad-org-name":"OrgName","iad-creative-name":"CreativeName","iad-click-date":"2016-05-26T12:14:32Z","iad-campaign-id":"1234567890","iad-attribution":"true","iad-lineitem-name":"LineName","iad-creative-id":"1234567890","iad-campaign-name":"CampaignName","iad-conversion-date":"2016-05-26T12:14:32Z"}}
2016-05-26 15:14:32.778 XX[1099:50625] 	[Adjust]v: 		environment            sandbox
2016-05-26 15:14:32.779 XX[1099:50625] 	[Adjust]v: 		event_buffering_enabled 0
2016-05-26 15:14:32.779 XX[1099:50625] 	[Adjust]v: 		idfa                   65BB1915-82DE-4473-8461-47512A76814B
2016-05-26 15:14:32.779 XX[1099:50625] 	[Adjust]v: 		idfv                   9A65D74E-2CBC-4FB2-97CE-89D38D7BB095
2016-05-26 15:14:32.779 XX[1099:50625] 	[Adjust]v: 		needs_response_details 0
2016-05-26 15:14:32.779 XX[1099:50625] 	[Adjust]v: 		source                 iad3
2016-05-26 15:14:33.810 XX[1099:50623] 	[Adjust]v: Response: {"message":"Unattributable SDK click ignored."}
2016-05-26 15:14:33.811 XX[1099:50623] 	[Adjust]i: Unattributable SDK click ignored.
```

* some details redacted and replaced with "XX"

**Comment by shooshx** [comment] 2016-05-26 12:58
Another related question - in iOS there's the convenient `[[Adjust idfa] UTF8String]` but I couldn't find a matching method in Android
Is there a convenient way to get this id in Android so I could use the forget URL?

**Comment by uerceg** [comment] 2016-05-26 14:18
Okay, so regarding your first post, install is indeed being tracked instantly after session package is actually being sent. But for some reason, you have this 8 seconds delay in sending this package. This package gets sent once your app receives `UIApplicationDidBecomeActiveNotification` from iOS. For some reason, your app is getting this delayed and this is the cause why do you see these things about 8 seconds delayed. Are you doing anything in `AppDelegate` which is causing this delay in receiving this notification from iOS?

And regarding second question, yes there is. Method is called `getGoogleAdId`. https://github.com/adjust/android_sdk#21-device-ids
