### ISSUE TITLE
[Crash] Crash at [ADJUtil writeObject:fileName:objectName:syncObject:]

### ISSUE THREAD

**Issue by ParveenTyagi2389** [adjust/ios_sdk#620] opened 2022-06-22 08:52 UTC
we are getting crash same mentioned below.

SDK version : 4.30.0

Crashed: io.adjust.PackageQueue
0 CoreFoundation 0x36550 _CFArrayReplaceValues + 840
1 CoreFoundation 0x3594c CFArrayAppendValue + 232
2 CoreFoundation 0x433c4 _flattenPlist + 292
3 CoreFoundation 0x43568 _flattenPlist + 712
4 CoreFoundation 0x43500 _flattenPlist + 608
5 CoreFoundation 0x43568 _flattenPlist + 712
6 CoreFoundation 0x43500 _flattenPlist + 608
7 CoreFoundation 0x42f44 __CFBinaryPlistWriteOrPresize + 236
8 Foundation 0x1b930 -[NSKeyedArchiver finishEncoding] + 548
9 Foundation 0x1cba4 -[NSKeyedArchiver encodedData] + 76
10 Foundation 0x1bfdc +[NSKeyedArchiver archivedDataWithRootObject:requiringSecureCoding:error:] + 124
11 Adjust 0x3e8e4 +[ADJUtil writeObject:fileName:objectName:syncObject:] + 337 (ADJUtil.m:337)
12 Adjust 0x2fd78 -[ADJPackageHandler writePackageQueueS:] + 324 (ADJPackageHandler.m:324)
13 Adjust 0x2f320 -[ADJPackageHandler addI📦] + 218 (ADJPackageHandler.m:218)
14 Adjust 0x411d4 __42+[ADJUtil launchInQueue:selfInject:block:]_block_invoke + 813 (ADJUtil.m:813)
15 libdispatch.dylib 0x2a84 _dispatch_call_block_and_release + 32
16 libdispatch.dylib 0x481c _dispatch_client_callout + 20
17 libdispatch.dylib 0xc004 _dispatch_lane_serial_drain + 620
18 libdispatch.dylib 0xcc00 _dispatch_lane_invoke + 404
19 libdispatch.dylib 0x174bc _dispatch_workloop_worker_thread + 764
20 libsystem_pthread.dylib 0x37a4 _pthread_wqthread + 276
21 libsystem_pthread.dylib 0xa74c start_wqthread + 8

**Comment by 405092901** [comment] 2022-07-04 03:22
the same to me

**Comment by ParveenTyagi2389** [comment] 2022-07-09 15:07
We are waiting to resolve that issue.
Please reply on it.

**Comment by Aditi3** [comment] 2022-07-11 10:43
Sorry about the trouble. It seems like this issue is a duplicate of #608. I'll be closing this issue to continue the discussion there.

**Closed** 2022-07-11 10:53 UTC
