### ISSUE TITLE
Deferred deep link callback is not triggered using LinkMe solution

### ISSUE THREAD

**Issue by mjinnatalabat** [adjust/ios_sdk#634] opened 2022-09-30 13:21 UTC
I was testing the below universal link for deferred deep link on iOS 16 version

https://***/?screen=voucher&adj_linkme=1&adj_t=tracker&adj_deep_link=app%3A%2F%2F%3Fscreen%3Dvoucher

**Scenario 1:** 
Clicked the link -> Opens intermediate page in safari to copy the link and go to app store -> Download the app -> Clicked "Allow paste" prompt after launching the app (iOS 16 specific) -> As a user, I waited 4 to 5 seconds on the onboarding screen to get the callback from adjust SDK -> Received callback through Adjust SDK delegate -> Proceed further to other screens -> **Deeplink worked as expected**

**Scenario 2:** 
Clicked the link -> Opens intermediate page in safari to copy the link and go to app store -> Download the app -> Clicked "Allow paste" prompt after launching the app (iOS 16 specific) -> As a user, I did not wait for the callback from Adjust SDK delegate -> Proceed further to other screens -> **Deferred deep link did not work**

I've implemented the delegate `- (BOOL)adjustDeeplinkResponse:(NSURL *)deep link` in `AppDelegate` and it did not trigger for scenario 2. Is there anything that causes **AdjustDelegate** to nil for not receiving the deep link callback? 

**Note:** `- (void)adjustAttributionChanged:(ADJAttribution *)attribution `delegate was called in both the scenarios. 

Please advise

**Comment by uerceg** [comment] 2022-10-04 12:39
Hi @mjinnatalabat,

Thanks for the detailed explanation. Did you uninstall your app and forgot your test device in testing console after running scenario 1 and before you ran scenario 2?

**Comment by mjinnatalabat** [comment] 2022-10-05 06:54
Thanks for the reply @uerceg 

Yeah, I did uninstall but did not forget the device id from the testing console because am using the linkme solution and I believe it works regardless of the IDFA if we use linkme.

**Comment by uerceg** [comment] 2022-10-05 07:45
Would it be possible to redo both scenarios with forgetting the device in between and let us know if scenario 2 worked as expected in that moment or are you still facing the same issue even with forgetting the device?

**Comment by uerceg** [comment] 2022-10-05 13:46
You can also use IDFV in case IDFA is not accessible.

**Comment by mjinnatalabat** [comment] 2022-10-05 13:53
IDFV also does not exist in adjust console

**Comment by uerceg** [comment] 2022-10-05 13:55
Oh, okay. :) Then you can check your SDK verbose logs and whenever something gets tracked, you will see `adid` parameter being sent as a response back which is Adjust identifier for your device. You can use that one as well in testing console to forget the device.

**Comment by xtealer** [comment] 2023-01-09 04:24
Getting this issue with `react-native` SDK... I believe the root cause comes from this package.

**Comment by uerceg** [comment] 2023-02-23 23:01
@mjinnatalabat Any update on this one? @xtealer Did you try the things which are suggested in that linked issue?

**Comment by Aditi3** [comment] 2023-10-13 09:54
I'm closing this for now, but feel free to reopen/comment if the issue persists, even with the latest SDK version.

**Closed by Aditi3** 2023-10-13 09:54 UTC
